spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # Cambiado a H2Dialect para mejor compatibilidad
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 25
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: false
        # Desactivar el uso de RETURNING
        jdbc.use_get_generated_keys: true
        # Utilizar secuencias para la generación de IDs
        id.new_generator_mappings: true

  sql:
    init:
      mode: always  # or 'embedded' if you want to limit it to embedded databases
      schema: classpath:schema.sql  # Point to your schema file

  modulith:
    republish-outstanding-events-on-restart: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Configuración adicional para H2
  h2:
    console:
      enabled: true
      path: /h2-console