spring:
    application:
        name: glaucomapp

    profiles:
        active: dev

    PYTHON_API_URL: ${PYTHON_API_URL}
    JWT_SECRET_KEY: ${JWT_SECRET_KEY}


        
server:
    port: 8000
    servlet:
        context-path: /